version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7-stretch-node
    steps:
      - checkout
      - run:
          name: Print current working directory
          command: pwd
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v2-poetry-deps-{{ checksum "poetry.lock" }}
            # Find the most recently generated cache used from this branch
            - v2-poetry-deps-{{ .Branch }}
            # Find the most recently generated cache used from any branch
            - v2-poetry-deps-
      - run: ./scripts/bootstrap.sh
      - run:
          name: Install dependencies
          command: poetry install
      - save_cache:
          key: v2-poetry-deps-{{ .Branch }}-{{ checksum "poetry.lock" }}
          paths:
            - .venv
            - /home/circleci/.cache/pre-commit
      - run:
          name: Lint
          command: poetry run precommit
      - run:
          name: pylint (slower, not run as pre-commit hook)
          command: poetry run pylint

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
